# NumPy Basics


In [4]:
import numpy as np


## Creating 1D Array

In [5]:
arr = np.array([10, 20, 30, 40, 50])
arr


array([10, 20, 30, 40, 50])

## Shape, Dimension and Data Type


In [6]:
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)

Shape: (5,)
Dimension: 1
Data Type: int64


## Creating 2D Array

In [7]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
matrix


array([[10, 20, 30],
       [40, 50, 60]])

## Shape and Dimensions of 2D Array

In [8]:
print("Shape:", matrix.shape)
print("Dimension:", matrix.ndim)

Shape: (2, 3)
Dimension: 2


## Reshape Array

In [9]:
matrix.reshape(3, 2)


array([[10, 20],
       [30, 40],
       [50, 60]])

## Statistical Operations


In [10]:
print("Mean:", np.mean(matrix))
print("Sum:", np.sum(matrix))
print("Maximum:", np.max(matrix))
print("Minimum:", np.min(matrix))

Mean: 35.0
Sum: 210
Maximum: 60
Minimum: 10


## Real-World Example: Traffic Data Analysis

In [11]:
vehicles = np.array([120, 95, 180, 76, 210, 155])

print("Vehicle Count:", vehicles)
print("Average:", np.mean(vehicles))
print("Highest:", np.max(vehicles))
print("Lowest:", np.min(vehicles))
print("Total:", np.sum(vehicles))

Vehicle Count: [120  95 180  76 210 155]
Average: 139.33333333333334
Highest: 210
Lowest: 76
Total: 836


## Vectorization Example


In [12]:
vehicles + 10


array([130, 105, 190,  86, 220, 165])

## Traffic Simulation

In [13]:
vehicles * 2

array([240, 190, 360, 152, 420, 310])